### ISSUE TITLE
CookBook/16 build error 

### ISSUE THREAD

**Issue by ZJLi2013** [ROCm-Developer-Tools/hip-tests#464]
### Problem Description

```yml
NAME="Ubuntu"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
ROCk module version 6.2.4 
Name:                    gfx1100
```

following: [sample build](https://github.com/ROCm/hip-tests/tree/develop/samples)

* build error on 02_CookBook/16_xxx
```yml

ld.lld: error: undefined symbol: __hip_fatbin
>>> referenced by square.cpp
>>>               /workspace/samples/build/2_Cookbook/16_assembly_to_executable/square_host.o:(__hip_fatbin_wrapper)
>>> did you mean: __hip_fatbin_
>>> defined in: /workspace/samples/build/2_Cookbook/16_assembly_to_executable/square_device.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

looks the default cmake can't find a link lib ?  or how should I setup ?

Thanks

### Operating System

Ubuntu 22.04

### CPU

Ryzen 

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.1.0

**Comment by ppanchad-amd** [comment]
Hi @ZJLi2013, internal ticket has been created to investigate your issue. Thanks!

**Comment by darren-amd** [comment]
Hi @ZJLi2013, 

A recent compiler patch introduced a change where clang is emitting the symbol `__hip_fatbin_` (with an underscore) instead of `__hip_fatbin` (without an underscore): https://github.com/llvm/llvm-project/pull/81700. The hip-tests were updated accordingly here: https://github.com/ROCm/hip-tests/commit/fba826fc3c6afc0deae298ecf0e9f7ee9901d990. I believe that you are running an older version of the compiler where `__hip_fatbin` is still being emitted. This mismatch is causing the reported error.

The solution is either to upgrade your ROCm version to the latest (6.2.0) or to try running the tests with the changes here reverted: https://github.com/ROCm/hip-tests/commit/fba826fc3c6afc0deae298ecf0e9f7ee9901d990. Please give that a try and let me know if you run into any further issues!
